### ISSUE TITLE
기능 목록

### ISSUE THREAD

**Issue by Joyykim** [Joyykim/ShortenURL-API#1]
- [x] 회원 가입, 로그인 기능 #3
- [x] URL 단축 #2 
- [x] 자신이 단축한 URL 히스토리 제공 #4
- [x] 쓰로틀링 #5
- [x] 결제 회원은 커스텀 URL 기능 #6
